name: rrweb-events
name: gametelemetry-web-sockets
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Output topic
    defaultValue: rrweb
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
