name: ws-events
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the output topic to write to.
    defaultValue: ws-input
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
