name: ws-events
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: ws-input
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
