name: Flask Web Gateway Source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: test
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
